# Generated by Django 4.0.4 on 2022-05-20 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digimon',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='digimon',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Playtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('petting', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1)),
                ('digimon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.digimon')),
            ],
        ),
    ]
